package cn.edu.tju.tiei.eshop.model;

import java.io.Serializable;

public class SearchProduct {
	/**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column product.id
    *
    * @mbg.generated
    */
    private int id;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column product.category_id
    *
    * @mbg.generated
    */
    private int categoryId;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column product.image
    *
    * @mbg.generated
    */
    private String image;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column product.name
    *
    * @mbg.generated
    */
    private String productName;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column product.market_price
    *
    * @mbg.generated
    */
	private Double marketPrice;
	
   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column product.is_on_sale
    *
    * @mbg.generated
    */
	private Boolean isOnSale;
	
   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column product.discount
    *
    * @mbg.generated
    */
	private Double discount;
	
   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column product.pub_date
    *
    * @mbg.generated
    */
	private String pubDate;
	
   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column product.stock_count
    *
    * @mbg.generated
    */
	private Integer stockCount;
	
   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column product.sale_count
    *
    * @mbg.generated
    */
	private Integer saleCount;
	
   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column product.summary
    *
    * @mbg.generated
    */
	private String summary;
	
   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column product.detail
    *
    * @mbg.generated
    */
	private String detail;

	/**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column category.name
    *
    * @mbg.generated
    */
    private String categoryName;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column category.description
    *
    * @mbg.generated
    */
    private String categoryDescription;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table category
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.id
     *
     * @return the value of product.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.id
     *
     * @param id the value for product.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.category_id
     *
     * @return the value of product.category_id
     *
     * @mbg.generated
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.category_id
     *
     * @param categoryId the value for product.category_id
     *
     * @mbg.generated
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.image
     *
     * @return the value of category.image
     *
     * @mbg.generated
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.image
     *
     * @param image the value for product.image
     *
     * @mbg.generated
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.name
     *
     * @return the value of product.name
     *
     * @mbg.generated
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.name
     *
     * @param productName the value for product.name
     *
     * @mbg.generated
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.market_price
     *
     * @return the value of product.market_price
     *
     * @mbg.generated
     */
    public Double getMarketPrice() {
        return marketPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.market_price
     *
     * @param marketPrice the value for product.market_price
     *
     * @mbg.generated
     */
    public void setMarketPrice(Double marketPrice) {
        this.marketPrice = marketPrice;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.is_on_sale
     *
     * @return the value of product.is_on_sale
     *
     * @mbg.generated
     */
    public Boolean getIsOnSale() {
        return isOnSale;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.is_on_sale
     *
     * @param isOnSale the value for product.is_on_sale
     *
     * @mbg.generated
     */
    public void setIsOnSale(Boolean isOnSale) {
        this.isOnSale = isOnSale;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.discount
     *
     * @return the value of product.discount
     *
     * @mbg.generated
     */
    public Double getDiscount() {
        return discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.discount
     *
     * @param discount the value for product.discount
     *
     * @mbg.generated
     */
    public void setDiscount(Double discount) {
        this.discount = discount;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.pub_date
     *
     * @return the value of product.pub_date
     *
     * @mbg.generated
     */
    public String getPubDate() {
        return pubDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.pub_date
     *
     * @param pubDate the value for product.pub_date
     *
     * @mbg.generated
     */
    public void setPubDate(String pubDate) {
        this.pubDate = pubDate;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.stock_count
     *
     * @return the value of product.stock_count
     *
     * @mbg.generated
     */
    public Integer getStockCount() {
        return stockCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.stock_count
     *
     * @param stockCount the value for product.stock_count
     *
     * @mbg.generated
     */
    public void setStockCount(Integer stockCount) {
        this.stockCount = stockCount;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.sale_count
     *
     * @return the value of product.sale_count
     *
     * @mbg.generated
     */
    public Integer getSaleCount() {
        return saleCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.sale_count
     *
     * @param saleCount the value for product.sale_count
     *
     * @mbg.generated
     */
    public void setSaleCount(Integer saleCount) {
        this.saleCount = saleCount;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.summary
     *
     * @return the value of product.summary
     *
     * @mbg.generated
     */
    public String getSummary() {
        return summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.summary
     *
     * @param summary the value for product.summary
     *
     * @mbg.generated
     */
    public void setSummary(String summary) {
    	this.summary = summary == null ? null : summary.trim();
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.detail
     *
     * @return the value of product.detail
     *
     * @mbg.generated
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.detail
     *
     * @param detail the value for product.detail
     *
     * @mbg.generated
     */
    public void setDetail(String detail) {
        this.detail = detail == null ? null : detail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.name
     *
     * @return the value of category.name
     *
     * @mbg.generated
     */
    public String getCategoryName() {
        return categoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.name
     *
     * @param categoryName the value for category.name
     *
     * @mbg.generated
     */
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName == null ? null : categoryName.trim();
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.description
     *
     * @return the value of category.description
     *
     * @mbg.generated
     */
    public String getCategoryDescription() {
        return categoryDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.description
     *
     * @param categoryDescription the value for category.description
     *
     * @mbg.generated
     */
    public void setCategoryDescription(String categoryDescription) {
        this.categoryDescription = categoryDescription == null ? null : categoryDescription.trim();
    }
}
