package cn.edu.tju.tiei.eshop.dao;

import cn.edu.tju.tiei.eshop.model.Login;
import cn.edu.tju.tiei.eshop.model.LoginExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LoginMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table login
	 * @mbg.generated
	 */
	long countByExample(LoginExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table login
	 * @mbg.generated
	 */
	int deleteByExample(LoginExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table login
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table login
	 * @mbg.generated
	 */
	int insert(Login record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table login
	 * @mbg.generated
	 */
	int insertSelective(Login record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table login
	 * @mbg.generated
	 */
	List<Login> selectByExample(LoginExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table login
	 * @mbg.generated
	 */
	Login selectByPrimaryKey(Integer integer);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table login
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("record") Login record, @Param("example") LoginExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table login
	 * @mbg.generated
	 */
	int updateByExample(@Param("record") Login record, @Param("example") LoginExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table login
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(Login record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table login
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Login record);
}