package cn.edu.tju.tiei.eshop.dao;

import cn.edu.tju.tiei.eshop.model.PaymentMethod;
import cn.edu.tju.tiei.eshop.model.PaymentMethodExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PaymentMethodMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_method
     *
     * @mbg.generated
     */
    long countByExample(PaymentMethodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_method
     *
     * @mbg.generated
     */
    int deleteByExample(PaymentMethodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_method
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_method
     *
     * @mbg.generated
     */
    int insert(PaymentMethod record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_method
     *
     * @mbg.generated
     */
    int insertSelective(PaymentMethod record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_method
     *
     * @mbg.generated
     */
    List<PaymentMethod> selectByExample(PaymentMethodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_method
     *
     * @mbg.generated
     */
    PaymentMethod selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_method
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") PaymentMethod record, @Param("example") PaymentMethodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_method
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") PaymentMethod record, @Param("example") PaymentMethodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_method
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PaymentMethod record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_method
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PaymentMethod record);
}