package cn.edu.tju.tiei.eshop.dao;

import cn.edu.tju.tiei.eshop.model.Rank;
import cn.edu.tju.tiei.eshop.model.RankExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RankMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rank
     *
     * @mbg.generated
     */
    long countByExample(RankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rank
     *
     * @mbg.generated
     */
    int deleteByExample(RankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rank
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Byte id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rank
     *
     * @mbg.generated
     */
    int insert(Rank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rank
     *
     * @mbg.generated
     */
    int insertSelective(Rank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rank
     *
     * @mbg.generated
     */
    List<Rank> selectByExample(RankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rank
     *
     * @mbg.generated
     */
    Rank selectByPrimaryKey(Byte id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rank
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Rank record, @Param("example") RankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rank
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Rank record, @Param("example") RankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rank
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Rank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rank
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Rank record);
}