package cn.edu.tju.tiei.eshop.dao;

import cn.edu.tju.tiei.eshop.model.SendMethod;
import cn.edu.tju.tiei.eshop.model.SendMethodExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SendMethodMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table send_method
     *
     * @mbg.generated
     */
    long countByExample(SendMethodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table send_method
     *
     * @mbg.generated
     */
    int deleteByExample(SendMethodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table send_method
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table send_method
     *
     * @mbg.generated
     */
    int insert(SendMethod record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table send_method
     *
     * @mbg.generated
     */
    int insertSelective(SendMethod record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table send_method
     *
     * @mbg.generated
     */
    List<SendMethod> selectByExample(SendMethodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table send_method
     *
     * @mbg.generated
     */
    SendMethod selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table send_method
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SendMethod record, @Param("example") SendMethodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table send_method
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SendMethod record, @Param("example") SendMethodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table send_method
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SendMethod record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table send_method
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SendMethod record);
}